### ISSUE TITLE
[feature request] get list of active workflows

### ISSUE THREAD

**Issue by naquarius** [knocklabs/knock-node#27]
hello!
would it be possible to expose an endpoint to get a list of active flows in the sdk similar to how the dashboard displays it?
we would like to create our set of tools for non-engineers and want to prevent them from manually typing in workflow ids.

thanks!

**Comment by naquarius** [comment]
thanks for the info @cjbell :D

**Comment by dangoslen** [comment]
@cjbell really late follow up here, but would you be open to a PR for some of this? It feels odd to have a `knock.workflows` object in the SDK and not be able to retrieve the workflows easily.
