### ISSUE TITLE
[feature request] object.listSubscriptions return total item count

### ISSUE THREAD

**Issue by naquarius** [knocklabs/knock-node#29]
hello!
We would like to get a count of total records for each subscription list, the use is to preview how many users will be impacted if we decided to send a specific notification. `PageInfo` type does not include a total count but this information is available in dashboard UI subscription list

Thanks!

**Comment by cjbell** [comment]
hey @naquarius, as an update here, we're exploring adding `total_count` to the `PageInfo` type and returning that for all paginated resources (including the subscriptions).

we're hoping to ship this tomorrow, with an update to the node SDK as well to support this change.

**Comment by naquarius** [comment]
thank you 💛 !! will keep an eye out for updates

**Comment by cjbell** [comment]
@naquarius this is now available in `0.4.21` (https://github.com/knocklabs/knock-node/releases/tag/v0.4.21)
