### ISSUE TITLE
feat: support Vercel Edge Runtime

### ISSUE THREAD

**Issue by Burry** [knocklabs/knock-node#38]
Hey Knock team! Knock's been featured in a few places by Vercel, and my team is leaning heavily on the Vercel Edge Runtime with Next.js, which doesn't support the full Node.js ecosystem. The `@knocklabs/node` package uses `axiom` and `jsonwebtoken` which are not compatible. Can you guys please build in support for the Edge Runtime by switching to the Web Fetch API and [jose](https://www.npmjs.com/package/jose)? Might require some fallbacks for Node.js runtimes before v17, which don't include `fetch`.

**Comment by connorlindsey** [comment]
Hi @Burry, as of the 0.6.0 release, the package will be compatible with Vercel's edge runtime
