### ISSUE TITLE
v0.6.0 not working

### ISSUE THREAD

**Issue by heymartinadams** [knocklabs/knock-node#47]
As mentioned in https://github.com/knocklabs/knock-node/pull/44, `v0.6.0` gives us the following error:

```
[TypeError: errors is not iterable]
```

when running the following operation:

```js
await knock.workflows.updateSchedules({
  data: { todoId, timeZone },
  schedule_ids: [dateStartReminder.scheduleId],
  scheduled_at: new Date(dateStart)
})
```

**Comment by connorlindsey** [comment]
Hey @heymartinadams, we found an issue with how we were formatting the error message returned from the API and are pushing a new version of the SDK now. Please upgrade to `0.6.1` and that should resolve things. Thanks!
